"""テンプレートのレンダリングと検証のテストモジュール。

このモジュールは、DocumentRenderクラスのテストを提供します。
テストは以下の3つの主要なカテゴリに分かれています:

1. 初期検証テスト
   - ファイルサイズ
   - エンコーディング
   - 構文
   - セキュリティ (静的解析)

2. ランタイム検証テスト
   - 再帰的構造
   - ゼロ除算
   - メモリ使用量

3. 検証の一貫性テスト
   - 初期検証とランタイム検証の結果の整合性
   - エラーメッセージの一貫性
"""

from io import BytesIO
from typing import (
    Any as AnyType,
)
from typing import (
    Callable,
    Dict,
    Optional,
)

import pytest
from _pytest.mark.structures import MarkDecorator

from features.document_render import (
    FORMAT_TYPE_COMPRESS,
    FORMAT_TYPE_COMPRESS_ALT,
    FORMAT_TYPE_KEEP,
    FORMAT_TYPE_KEEP_ALT,
    FORMAT_TYPE_REMOVE_ALL,
    MAX_FORMAT_TYPE,
    MIN_FORMAT_TYPE,
    DocumentRender,
)

# Constants for better readability in tests
INITIAL_VALID: bool = True
INITIAL_INVALID: bool = False
RUNTIME_VALID: bool = True
RUNTIME_INVALID: bool = False
STRICT_UNDEFINED: bool = True
NON_STRICT_UNDEFINED: bool = False
EXPECTED_NO_ERROR: Optional[str] = None
EXPECTED_NO_CONTENT: Optional[str] = None


UNIT: MarkDecorator = pytest.mark.unit
SET_TIMEOUT: MarkDecorator = pytest.mark.timeout(10)


@pytest.fixture
def create_template_file() -> Callable[[bytes, str], BytesIO]:
    """テスト用のテンプレートファイルを作成するフィクスチャ。

    Returns:
        Callable[[bytes, str], BytesIO]: テンプレートファイルを作成する関数
    """

    def _create_file(content: bytes, filename: str = "template.txt") -> BytesIO:
        file: BytesIO = BytesIO(content)
        file.name = filename
        return file

    return _create_file


@UNIT
@SET_TIMEOUT
@pytest.mark.parametrize(
    (
        "template_content",
        "format_type",
        "is_strict_undefined",
        "context",
        "expected_initial_valid",
        "expected_runtime_valid",
        "expected_content",
        "expected_initial_error",
        "expected_runtime_error",
    ),
    [
        pytest.param(
            b"",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filesize_empty_success_strict",
        ),
        pytest.param(
            b"a" * (30 * 1024 * 1024),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "a" * (30 * 1024 * 1024),
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filesize_max_exact_success_strict",
        ),
        pytest.param(
            b"a" * (30 * 1024 * 1024 + 1),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            f"Template file size exceeds maximum limit of {30 * 1024 * 1024} bytes",
            f"Template file size exceeds maximum limit of {30 * 1024 * 1024} bytes",
            id="test_render_filesize_max_exceeded_fail_strict",
        ),
        pytest.param(
            b"\x80\x81\x82\x83",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template file contains invalid UTF-8 bytes",
            "Template file contains invalid UTF-8 bytes",
            id="test_render_encoding_invalid_utf8_fail_strict",
        ),
        pytest.param(
            b"\x00",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template file contains invalid binary data",
            "Template file contains invalid binary data",
            id="test_render_encoding_null_byte_only_fail_strict",
        ),
        pytest.param(
            b"Hello\x00World",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template file contains invalid binary data",
            "Template file contains invalid binary data",
            id="test_render_encoding_null_byte_in_text_fail_strict",
        ),
        pytest.param(
            b"Hello {{ name }!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "unexpected '}'",
            "unexpected '}'",
            id="test_render_syntax_error_unmatched_brace_fail_strict",
        ),
        pytest.param(
            b"{% macro input() %}{% endmacro %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'macro' tag is not allowed",
            "Template security error: 'macro' tag is not allowed",
            id="test_render_initial_security_macro_tag_fail_strict",
        ),
        pytest.param(
            b"{{ 10 / value }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"value": 0},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: division by zero",
            id="test_render_runtime_division_by_zero_context_fail_strict",
        ),
        pytest.param(
            b"{{ 10 / value }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"value": 0},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: division by zero",
            id="test_render_runtime_division_by_zero_context_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_valid_context_unexpected_fail_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_valid_context_unexpected_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ undefined }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'undefined' is undefined",
            id="test_render_runtime_undefined_var_context_fail_strict",
        ),
        pytest.param(
            b"Hello {{ undefined }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_var_context_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_variable_basic_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            FORMAT_TYPE_REMOVE_ALL,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!\nGood bye World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_format_remove_all_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!\n\nGood bye World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_format_compress_alt_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            FORMAT_TYPE_KEEP_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!\n\n\n  \nGood bye World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_format_keep_alt_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            FORMAT_TYPE_COMPRESS,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!\n\nGood bye World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_format_compress_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            FORMAT_TYPE_KEEP,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello World!\n\n\n  \nGood bye World!",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_format_keep_success_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_var_success_non_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'name' is undefined",
            id="test_render_runtime_undefined_var_fail_strict",
        ),
        pytest.param(
            b"Hello {{ first_name }} {{ last_name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"first_name": "John"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello John !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_multiple_vars_partial_success_non_strict",
        ),
        pytest.param(
            b"Hello {{ first_name }} {{ last_name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"first_name": "John"},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'last_name' is undefined",
            id="test_render_runtime_multiple_vars_partial_fail_strict",
        ),
        pytest.param(
            b"{% if undefined_var %}Show{% else %}Hide{% endif %}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hide",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_in_condition_success_non_strict",
        ),
        pytest.param(
            b"{% if undefined_var %}Show{% else %}Hide{% endif %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'undefined_var' is undefined",
            id="test_render_runtime_undefined_in_condition_fail_strict",
        ),
        pytest.param(
            b"{{ name if name is defined else 'Anonymous' }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Anonymous",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_defined_check_fallback_success_non_strict",
        ),
        pytest.param(
            b"{{ name if name is defined else 'Anonymous' }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Anonymous",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_defined_check_fallback_success_strict",
        ),
        pytest.param(
            b"{{ user.name }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_nested_undefined_success_non_strict",
        ),
        pytest.param(
            b"{{ user.name }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'user' is undefined",
            id="test_render_runtime_nested_undefined_fail_strict",
        ),
        pytest.param(
            b"\x80\x81\x82\x83",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template file contains invalid UTF-8 bytes",
            "Template file contains invalid UTF-8 bytes",
            id="test_render_initial_encoding_invalid_utf8_fail_strict",
        ),
        pytest.param(
            b"Hello {{ name }!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "unexpected '}'",
            "unexpected '}'",
            id="test_render_initial_syntax_error_unmatched_brace_fail_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            MIN_FORMAT_TYPE - 1,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Validation error: Input should be greater than or equal to 0 at 'format_type'",
            id="test_render_runtime_invalid_format_type_below_min_fail_strict",
        ),
        pytest.param(
            b"Hello {{ name }}!\n\n\n  \nGood bye {{ name }}!",
            MAX_FORMAT_TYPE + 1,
            STRICT_UNDEFINED,
            {"name": "World"},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Validation error: Input should be less than or equal to 4 at 'format_type'",
            id="test_render_runtime_invalid_format_type_above_max_fail_strict",
        ),
        pytest.param(
            b"{{ 10 / value }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"value": 0},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: division by zero",
            id="test_render_runtime_division_by_zero_fail_strict",
        ),
        pytest.param(
            (
                b"Current Date: {{ current_date | date('%Y-%m-%d') }}\n"
                b"Last Updated: {{ last_updated | date('%Y-%m-%d %H:%M:%S') }}\n"
                b"Next Review: {{ next_review | date('%B %d, %Y') }}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {
                "current_date": "2024-03-20",
                "last_updated": "2024-03-20T15:30:45",
                "next_review": "2024-06-20",
            },
            INITIAL_VALID,
            RUNTIME_VALID,
            ("Current Date: 2024-03-20\nLast Updated: 2024-03-20 15:30:45\nNext Review: June 20, 2024"),
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filter_date_success_strict",
        ),
        pytest.param(
            (
                b"Unix Timestamp: {{ unix_timestamp | date('%Y-%m-%d %H:%M:%S') }}\n"
                b"Millisecond Timestamp: {{ ms_timestamp | date('%Y-%m-%d %H:%M:%S.%f') }}\n"
                b"Formatted Time: {{ unix_timestamp | date('%H:%M') }}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {
                "unix_timestamp": "2024-03-20T15:30:45",  # ISO 8601形式
                "ms_timestamp": "2024-03-20T15:30:45.123",  # ミリ秒付きISO 8601形式
            },
            INITIAL_VALID,
            RUNTIME_VALID,
            "Unix Timestamp: 2024-03-20 15:30:45\nMillisecond Timestamp: 2024-03-20 15:30:45.123000\nFormatted Time: 15:30",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filter_timestamp_success_strict",
        ),
        pytest.param(
            b"Historic Date: {{ historic_date | date('%Y-%m-%d %H:%M:%S') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {
                "historic_date": "1969-01-01T00:00:00",  # ISO 8601形式
            },
            INITIAL_VALID,
            RUNTIME_VALID,
            "Historic Date: 1969-01-01 00:00:00",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filter_historic_date_success_strict",
        ),
        pytest.param(
            (
                b"ISO String: {{ iso_date | date('%d %b %Y') }}\n"
                b"ISO with TZ: {{ iso_with_tz | date('%Y-%m-%d %H:%M %Z') }}\n"
                b"Future Date: {{ future_date | date('%A, %B %d, %Y') }}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {
                "iso_date": "2024-12-31T23:59:59",
                "iso_with_tz": "2024-06-15T12:30:45+09:00",
                "future_date": "2025-01-01T00:00:00",
            },
            INITIAL_VALID,
            RUNTIME_VALID,
            "ISO String: 31 Dec 2024\nISO with TZ: 2024-06-15 12:30 UTC+09:00\nFuture Date: Wednesday, January 01, 2025",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_filter_iso_date_formats_success_strict",
        ),
        pytest.param(
            b"{{ invalid_date | date('%Y-%m-%d') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"invalid_date": "not-a-date"},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: Invalid date format",
            id="test_render_runtime_filter_invalid_date_fail_strict",
        ),
        pytest.param(
            b"{{ date | date('%Y-%m-%d') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"date": None},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: 'NoneType' object has no attribute 'replace'",
            id="test_render_runtime_filter_null_date_fail_strict",
        ),
        pytest.param(
            b"{{ ''.__class__ }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted attribute '__class__' is forbidden.",
            "Template security validation failed: Access to restricted attribute '__class__' is forbidden.",
            id="test_render_initial_security_injection_class_attr_fail_strict",
        ),
        pytest.param(
            b"{{ ''.__class__.__mro__ }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted attribute '__mro__' is forbidden.",
            "Template security validation failed: Access to restricted attribute '__mro__' is forbidden.",
            id="test_render_initial_security_injection_mro_attr_fail_strict",
        ),
        pytest.param(
            b"{{ ''.__class__.__mro__[1].__subclasses__() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted attribute '__subclasses__' is forbidden.",
            "Template security validation failed: Access to restricted attribute '__subclasses__' is forbidden.",
            id="test_render_initial_security_injection_subclasses_attr_fail_strict",
        ),
        pytest.param(
            b"{{ getattr('', '__class__') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'getattr()' is forbidden.",
            "Template security validation failed: Call to restricted function 'getattr()' is forbidden.",
            id="test_render_initial_security_injection_getattr_call_fail_strict",
        ),
        pytest.param(
            b"{{ self.__init__.__globals__['os'] }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"self": object()},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted item 'os' is forbidden.",
            "Template security validation failed: Access to restricted item 'os' is forbidden.",
            id="test_render_initial_security_injection_globals_item_fail_strict",
        ),
        pytest.param(
            b"{% import 'os' as os %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'import' tag is not allowed",
            "Template security error: 'import' tag is not allowed",
            id="test_render_initial_security_injection_import_tag_fail_strict",
        ),
        pytest.param(
            b"{% extends 'base.html' %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'extends' tag is not allowed",
            "Template security error: 'extends' tag is not allowed",
            id="test_render_initial_security_injection_extends_tag_fail_strict",
        ),
        pytest.param(
            b"{{ eval('1+1') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"eval": eval},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'eval()' is forbidden.",
            "Template security validation failed: Call to restricted function 'eval()' is forbidden.",
            id="test_render_initial_security_injection_eval_call_fail_strict",
        ),
        pytest.param(
            b"{{ exec('import os') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"exec": exec},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'exec()' is forbidden.",
            "Template security validation failed: Call to restricted function 'exec()' is forbidden.",
            id="test_render_initial_security_injection_exec_call_fail_strict",
        ),
        pytest.param(
            b"{{ os.system('ls') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"os": __import__("os")},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'os' is forbidden.",
            "Template security validation failed: Use of restricted variable 'os' is forbidden.",
            id="test_render_initial_security_injection_os_var_fail_strict",
        ),
        pytest.param(
            b"{{ sys.modules }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"sys": __import__("sys")},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'sys' is forbidden.",
            "Template security validation failed: Use of restricted variable 'sys' is forbidden.",
            id="test_render_initial_security_injection_sys_var_fail_strict",
        ),
        pytest.param(
            b"{{ builtins.open('/etc/passwd').read() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"builtins": __import__("builtins")},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'builtins' is forbidden.",
            "Template security validation failed: Use of restricted variable 'builtins' is forbidden.",
            id="test_render_initial_security_injection_builtins_var_fail_strict",
        ),
        pytest.param(
            b"{{ setattr(obj, 'attr', 'value') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"setattr": setattr, "obj": object()},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'setattr()' is forbidden.",
            "Template security validation failed: Call to restricted function 'setattr()' is forbidden.",
            id="test_render_initial_security_injection_setattr_call_fail_strict",
        ),
        pytest.param(
            b"{{ delattr(obj, 'attr') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"delattr": delattr, "obj": type("Dummy", (), {"attr": 1})()},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'delattr()' is forbidden.",
            "Template security validation failed: Call to restricted function 'delattr()' is forbidden.",
            id="test_render_initial_security_injection_delattr_call_fail_strict",
        ),
        pytest.param(
            b"{{ locals() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"locals": locals},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Call to restricted function 'locals()' is forbidden.",
            "Template security validation failed: Call to restricted function 'locals()' is forbidden.",
            id="test_render_initial_security_injection_locals_call_fail_strict",
        ),
        pytest.param(
            b"{{ config }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"config": {}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            id="test_render_initial_security_injection_config_var_fail_strict",
        ),
        pytest.param(
            b"{{ obj.__base__ }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"obj": "test"},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted attribute '__base__' is forbidden.",
            "Template security validation failed: Access to restricted attribute '__base__' is forbidden.",
            id="test_render_initial_security_injection_base_attr_fail_strict",
        ),
        pytest.param(
            b"{{ my_dict['os'] }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"my_dict": {"os": "value"}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Access to restricted item 'os' is forbidden.",
            "Template security validation failed: Access to restricted item 'os' is forbidden.",
            id="test_render_initial_security_injection_os_item_fail_strict",
        ),
        pytest.param(
            b"{% set my_os = os %}{{ my_os }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"os": "fake_os"},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Assignment of restricted variable 'os' is forbidden.",
            "Template security validation failed: Assignment of restricted variable 'os' is forbidden.",
            id="test_render_initial_security_injection_os_assign_fail_strict",
        ),
        pytest.param(
            b"{% set my_eval = eval %}{{ my_eval('1') }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"eval": eval},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Assignment of restricted variable 'eval' is forbidden.",
            "Template security validation failed: Assignment of restricted variable 'eval' is forbidden.",
            id="test_render_initial_security_injection_eval_assign_fail_strict",
        ),
        pytest.param(
            b"{% set d = {} %}{% do d.update({'self': d}) %}{{ d }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'do' tag is not allowed",
            "Template security error: 'do' tag is not allowed",
            id="test_render_initial_security_do_tag_recursive_dict_fail_strict",
        ),
        pytest.param(
            b"{% set l = [[]] %}{% do l[0].append(l) %}{{ l }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'do' tag is not allowed",
            "Template security error: 'do' tag is not allowed",
            id="test_render_initial_security_do_tag_recursive_list_fail_strict",
        ),
        pytest.param(
            b"{% set d = {} %}{% set l = [d] %}{% do d.update({'list': l}) %}{{ l }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'do' tag is not allowed",
            "Template security error: 'do' tag is not allowed",
            id="test_render_initial_security_do_tag_recursive_mixed_fail_strict",
        ),
        pytest.param(
            (
                b"{% for i in range(3) %}\n"
                b"  {% for j in range(2) %}\n"
                b"    {% if i > 0 and j > 0 %}\n"
                b"      {{ i }} - {{ j }}: {{ data[i][j] if data and i < data|length and j < data[i]|length else 'N/A' }}\n"
                b"    {% else %}\n"
                b"      {{ i }} - {{ j }}: Start\n"
                b"    {% endif %}\n"
                b"  {% endfor %}\n"
                b"{% endfor %}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"data": [[1, 2], [3, 4], [5, 6]]},
            INITIAL_VALID,
            RUNTIME_VALID,
            (
                "\n      0 - 0: Start\n\n      0 - 1: Start\n\n      1 - 0: Start\n\n"
                "      1 - 1: 4\n\n      2 - 0: Start\n\n      2 - 1: 6\n\n"
            ),
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_logic_complex_loops_conditionals_success_strict",
        ),
        pytest.param(
            b"{{ undefined_var if undefined_var is defined else 'Default' }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Default",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_edgecase_undefined_fallback_success_non_strict",
        ),
        pytest.param(
            b"{% for i in range(count) %}Line {{ i }}\n{% endfor %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"count": 50},  # 1000から50に減らす
            INITIAL_VALID,
            RUNTIME_VALID,
            "\n".join([f"Line {i}" for i in range(50)]) + "\n",  # Add trailing newline
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_edgecase_many_lines_success_strict",
        ),
        pytest.param(
            "{{ emoji }} {{ japanese }}".encode("utf-8"),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"emoji": "😁😂🤣😃", "japanese": "こんにちは世界"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "😁😂🤣😃 こんにちは世界",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_edgecase_unicode_success_strict",
        ),
        pytest.param(
            b"<html><body>{{ content | safe }}</body></html>",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"content": "<h1>Title</h1><p>Paragraph with <b>bold</b> text</p>"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "<html><body>&lt;h1&gt;Title&lt;/h1&gt;&lt;p&gt;Paragraph with &lt;b&gt;bold&lt;/b&gt; text&lt;/p&gt;</body></html>",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_edgecase_html_safe_filter_autoescaped_success_strict",
        ),
        pytest.param(
            b"<html><body>{{ content | safe }}</body></html>",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"content": "<script>alert('XSS')</script>"},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            (
                "Template rendering error: 1 validation error for HTMLContent\n"
                "content\n"
                "  Value error, HTML content contains potentially unsafe elements "
                "[type=value_error, input_value=\"<script>alert('XSS')</script>\", "
                "input_type=str]\n"
                "    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
            ),
            id="test_render_runtime_security_unsafe_html_fail_strict",
        ),
        pytest.param(
            b"<html><body>{{ content }}</body></html>",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"content": "<script>alert('XSS')</script>"},
            INITIAL_VALID,
            RUNTIME_VALID,
            "<html><body>&lt;script&gt;alert(&#39;XSS&#39;)&lt;/script&gt;</body></html>",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_edgecase_html_autoescape_success_strict",
        ),
        pytest.param(
            (
                b"{% macro input(name, value='', type='text') -%}\n"
                b'    <input type="{{ type }}" name="{{ name }}" value="{{ value }}">\n'
                b"{%- endmacro %}\n\n"
                b"{{ input('username') }}\n"
                b"{{ input('password', type='password') }}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'macro' tag is not allowed",
            "Template security error: 'macro' tag is not allowed",
            id="test_render_initial_security_macro_definition_fail_strict",
        ),
        pytest.param(
            (
                b"{% macro input(name, value='', type='text') -%}\n"
                b'    <input type="{{ type }}" name="{{ name }}" value="{{ value }}">\n'
                b"{%- endmacro %}\n\n"
                b"{{ input('username') }}\n"
                b"{{ input('password', type='password') }}"
            ),
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: 'macro' tag is not allowed",
            "Template security error: 'macro' tag is not allowed",
            id="test_render_initial_security_macro_definition_fail_non_strict",
        ),
        pytest.param(
            b"{%- call input('username') %}{% endcall %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'input' is undefined",
            id="test_render_runtime_logic_call_tag_undefined_fail_strict",
        ),
        pytest.param(
            b"{%- call input('username') %}{% endcall %}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "Template rendering error: sequence item 0: expected str instance, CustomUndefined found",
            id="test_render_runtime_logic_call_tag_undefined_fail_non_strict",
        ),
        pytest.param(
            b"{% set x = request.args %}{{ x }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"request": {"args": {"debug": "true"}}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'request' is forbidden.",
            "Template security validation failed: Use of restricted variable 'request' is forbidden.",
            id="test_render_initial_security_injection_request_var_fail_strict",
        ),
        pytest.param(
            b"{% set x = request.args %}{{ x }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"request": {"args": {"debug": "true"}}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'request' is forbidden.",
            "Template security validation failed: Use of restricted variable 'request' is forbidden.",
            id="test_render_initial_security_injection_request_var_fail_non_strict",
        ),
        pytest.param(
            b"{{ config.items() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"config": {"secret": "sensitive_data"}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            id="test_render_initial_security_injection_config_items_fail_strict",
        ),
        pytest.param(
            b"{{ config.items() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"config": {"secret": "sensitive_data"}},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            "Template security validation failed: Use of restricted variable 'config' is forbidden.",
            id="test_render_initial_security_injection_config_items_fail_non_strict",
        ),
        pytest.param(
            b"{% set x = [] %}{% set _ = x.append(x) %}{{ x }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "[[...]]",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_edgecase_recursive_list_success_strict",
        ),
        pytest.param(
            b"{% set x = [] %}{% set _ = x.append(x) %}{{ x }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "[[...]]",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_edgecase_recursive_list_success_non_strict",
        ),
        pytest.param(
            b"{% for i in range(999999999) %}{{ i }}{% endfor %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: loop range exceeds maximum limit of 100000",
            "Template security error: loop range exceeds maximum limit of 100000",
            id="test_render_initial_security_large_loop_range_999M_fail_strict",
        ),
        pytest.param(
            b"{% for i in range(999999999) %}{{ i }}{% endfor %}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_INVALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            "Template security error: loop range exceeds maximum limit of 100000",
            "Template security error: loop range exceeds maximum limit of 100000",
            id="test_render_initial_security_large_loop_range_999M_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ user.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'user' is undefined",
            id="test_render_runtime_nested_undefined_context_fail_strict",
        ),
        pytest.param(
            b"Hello {{ user.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_nested_undefined_context_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ user.profile.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'user' is undefined",
            id="test_render_runtime_multi_level_nested_undefined_context_fail_strict",
        ),
        pytest.param(
            b"Hello {{ user.profile.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_multi_level_nested_undefined_context_fail_non_strict",
        ),
        pytest.param(
            b"Hello {{ user.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {"user": {}},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'dict object' has no attribute 'name'",
            id="test_render_runtime_partial_nested_undefined_context_fail_strict",
        ),
        pytest.param(
            b"{{ undefined.method() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'undefined' is undefined",
            id="test_render_runtime_undefined_method_call_context_fail_strict",
        ),
        pytest.param(
            b"{{ items[0] }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'items' is undefined",
            id="test_render_runtime_undefined_index_access_context_fail_strict",
        ),
        pytest.param(
            b"{{ 'prefix_' + undefined + '_suffix' }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'undefined' is undefined",
            id="test_render_runtime_undefined_in_expression_context_fail_strict",
        ),
        pytest.param(
            b"{{ 'prefix_' + undefined + '_suffix' }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "_suffix",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_in_expression_context_fail_non_strict",
        ),
        pytest.param(
            b"{% if condition %}{{ value }}{% endif %}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'condition' is undefined",
            id="test_render_runtime_undefined_in_condition_value_context_fail_strict",
        ),
        pytest.param(
            b"{{ undefined|upper }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'undefined' is undefined",
            id="test_render_runtime_undefined_with_filter_context_fail_strict",
        ),
        pytest.param(
            b"{{ var1 ~ var2 ~ var3 }}",
            FORMAT_TYPE_COMPRESS_ALT,
            STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'var1' is undefined",
            id="test_render_runtime_multiple_undefined_concat_context_fail_strict",
        ),
        pytest.param(
            b"Hello {{ user.name }}!",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {"user": {}},
            INITIAL_VALID,
            RUNTIME_VALID,
            "Hello !",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_partial_nested_undefined_context_fail_non_strict",
        ),
        pytest.param(
            b"{{ undefined.method() }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_method_call_context_fail_non_strict",
        ),
        pytest.param(
            b"{{ items[0] }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            "'items' is undefined",
            id="test_render_runtime_undefined_index_access_context_fail_non_strict",
        ),
        pytest.param(
            b"{% if condition %}{{ value }}{% endif %}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_in_condition_value_context_fail_non_strict",
        ),
        pytest.param(
            b"{{ undefined|upper }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_undefined_with_filter_context_fail_non_strict",
        ),
        pytest.param(
            b"{{ var1 ~ var2 ~ var3 }}",
            FORMAT_TYPE_COMPRESS_ALT,
            NON_STRICT_UNDEFINED,
            {},
            INITIAL_VALID,
            RUNTIME_VALID,
            "",
            EXPECTED_NO_ERROR,
            EXPECTED_NO_ERROR,
            id="test_render_runtime_multiple_undefined_concat_context_fail_non_strict",
        ),
        pytest.param(
            b"{{ large_data }}",
            FORMAT_TYPE_KEEP,
            STRICT_UNDEFINED,
            {"large_data": "a" * (DocumentRender.MAX_MEMORY_SIZE_BYTES + 10)},
            INITIAL_VALID,
            RUNTIME_INVALID,
            EXPECTED_NO_CONTENT,
            EXPECTED_NO_ERROR,
            f"Memory consumption exceeds maximum limit of {DocumentRender.MAX_MEMORY_SIZE_BYTES} bytes",
            id="test_render_runtime_memory_limit_exceeded_by_context_fail_strict",
        ),
    ],
)
def test_render_template(
    create_template_file: Callable[[bytes, str], BytesIO],
    template_content: bytes,
    format_type: int,
    is_strict_undefined: bool,
    context: Dict[str, AnyType],
    expected_initial_valid: bool,
    expected_runtime_valid: bool,
    expected_content: Optional[str],
    expected_initial_error: Optional[str],
    expected_runtime_error: Optional[str],
) -> None:
    """初期検証とランタイム検証の一貫性を確認する。

    Args:
        create_template_file: テンプレートファイル作成用フィクスチャ
        template_content: テンプレートの内容
        format_type: フォーマットタイプ
        is_strict_undefined: 未定義変数を厳密にチェックするかどうか
        context: テンプレートに適用するコンテキスト
        expected_initial_valid: 初期検証が成功することが期待されるかどうか
        expected_runtime_valid: ランタイム検証が成功することが期待されるかどうか
        expected_content: 期待される出力内容
        expected_initial_error: 初期検証の期待されるエラーメッセージ
        expected_runtime_error: ランタイム検証の期待されるエラーメッセージ
    """
    # Arrange
    template_file: BytesIO = create_template_file(template_content, "template.txt")

    # Act
    render = DocumentRender(template_file)

    # Act & Assert for template validation
    assert render.is_valid_template == expected_initial_valid, (
        f"expected_initial_valid isn't match.\nExpected: {expected_initial_valid}\nGot: {render.is_valid_template}"
    )
    assert render.error_message == expected_initial_error, (
        f"expected_initial_error isn't match.\nExpected: {expected_initial_error}\nGot: {render.error_message}"
    )

    # Act
    apply_result: bool = render.apply_context(context, format_type, is_strict_undefined)

    # Assert
    assert apply_result == expected_runtime_valid, (
        f"expected_runtime_valid isn't match.\nExpected: {expected_runtime_valid}\nGot: {apply_result}"
    )
    assert render.render_content == expected_content, (
        f"expected_content isn't match.\nExpected: {expected_content}\nGot: {render.render_content}"
    )
    assert render.error_message == expected_runtime_error, (
        f"expected_runtime_error isn't match.\nExpected: {expected_runtime_error}\nGot: {render.error_message}"
    )
